# Generated by Django 4.0.4 on 2022-06-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='xiaoqu_wailai',
            fields=[
                ('wailai_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=12, null=True)),
                ('age', models.IntegerField()),
                ('yezhu_id', models.CharField(max_length=12)),
            ],
        ),
    ]
